using Microsoft.AspNetCore.Mvc;

namespace NavAid.Api.Models;

public enum ExplanationSource
{
    /// <summary>Generated by the language model and verified against the payload.</summary>
    Model,

    /// <summary>Generated deterministically from the payload. No model involved.</summary>
    Template
}

public sealed class ExplanationResult
{
    public required ExplanationSource Source { get; init; }
    public required IReadOnlyList<ExplanationSection> Sections { get; init; }
    public required ExplanationPayload Payload { get; init; }

    /// <summary>Null when Source is Template — there is nothing to verify.</summary>
    public VerificationReport? Verification { get; init; }

    /// <summary>Populated when the model was attempted and failed, for the panel banner.</summary>
    public string? FallbackReason { get; init; }
}

public sealed class ExplanationSection
{
    public required string Heading { get; init; }
    public required string Body { get; init; }

    /// <summary>Fact IDs this section draws on. Rendered as the grounding list.</summary>
    public required IReadOnlyList<string> CitedFactIds { get; init; }

    /// True when the body is builder-supplied text passed through unchanged.
    /// Verification applies only to generated prose: checking text the system
    /// itself wrote produces findings that say nothing about the model.
    public bool IsVerbatim { get; init; }
}
